# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 30 Dec 2022 20:34:36 +0000
*	@ALL	1
*	@user	1
*	@root%5feditor	16
