<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: geraldine
 * Date: Thu, 04 Apr 2024 07:46:24 +0000
 */

$conf['title'] = 'MKULTRAVIOLENCE';
$conf['template'] = 'mindthedark';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['usewordblock'] = 0;
$conf['locktime'] = 60*60;
$conf['gdlib'] = '1';
$conf['jpg_quality'] = 100;
$conf['fetchsize'] = 52428800;
$conf['useslash'] = 1;
$conf['send404'] = 1;
$conf['defer_js'] = 0;
$conf['plugin']['wrap']['darkTpl'] = 1;
$conf['tpl']['mindthedark']['theme'] = 'dark';
$conf['tpl']['mindthedark']['autoDark'] = 1;
$conf['tpl']['mindthedark']['userChoice'] = 1;
$conf['tpl']['bootstrap3']['socialShareProviders'] = 'facebook,linkedin,microsoft-teams,pinterest,whatsapp,reddit,twitter,telegram,yammer,google-plus';
