# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Fri, 30 Dec 2022 20:34:36 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

geraldine:$2y$10$dlFYThoGBGnXj5Ew2g5zyee3VLpgQWuiI8XdLOkR/xIAEy1o/Gl8O:Sven Maso:masosven@protonmail.com:admin,user
nyll:$2y$10$5olcS2hDeAH360TsxXeNtO/8mwzUjYr4g3gPW1kh/uw7VD7J0I3TC:Nyll:nvbc28@gmail.com:user,root_editor
thread:$2y$10$XIwNVPifTSRroBVfcVXlrOWc4TcCf45ldavpOLmaTdyQkq3C9BeZm:Lmao:howaverage@yahoo.com:user,root_editor
avery:$2y$10$mO4rnhNHVyHWGr6ZiWCEL.S12cbz1ILdou6PFck.s3X6M4798o24i:Avery:armortrimmer69@tfwno.gf:user,root_editor
tendril:$2y$10$rrqx7Xb4xRvUHHejBor0YOWPkSQJDgm72Nnn53ecsARLEwwMFkDqO:Little Man:pissdrinker@cock.li:user,root_editor
